controller_list:
  - name: /scaled_pos_joint_traj_controller
    action_ns: 'follow_joint_trajectory'
    type: FollowJointTrajectory
    joints:
      - ur_shoulder_pan_joint
      - ur_shoulder_lift_joint
      - ur_elbow_joint
      - ur_wrist_1_joint
      - ur_wrist_2_joint
      - ur_wrist_3_joint
  - name: /gripper
    action_ns: ''
    type: GripperCommand
    joints:
      - finger_joint

